package com.liftstore.entity;
// Generated 16 Oca 2021 12:42:51 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bakim generated by hbm2java
 */
@Entity
@Table(name = "bakim", catalog = "liftstore")
public class Bakim implements java.io.Serializable {

	private Integer bakimId;
	private Lift lift;
	private String bakimAdi;
	private float bakimFiyat;
	private Date bakimTarihi;

	public Bakim() {
	}

	public Bakim(Lift lift, String bakimAdi, float bakimFiyat, Date bakimTarihi) {
		this.lift = lift;
		this.bakimAdi = bakimAdi;
		this.bakimFiyat = bakimFiyat;
		this.bakimTarihi = bakimTarihi;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "bakimID", unique = true, nullable = false)
	public Integer getBakimId() {
		return this.bakimId;
	}

	public void setBakimId(Integer bakimId) {
		this.bakimId = bakimId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "liftId", nullable = false)
	public Lift getLift() {
		return this.lift;
	}

	public void setLift(Lift lift) {
		this.lift = lift;
	}

	@Column(name = "bakimAdi", nullable = false, length = 100)
	public String getBakimAdi() {
		return this.bakimAdi;
	}

	public void setBakimAdi(String bakimAdi) {
		this.bakimAdi = bakimAdi;
	}

	@Column(name = "bakimFiyat", nullable = false, precision = 12, scale = 0)
	public float getBakimFiyat() {
		return this.bakimFiyat;
	}

	public void setBakimFiyat(float bakimFiyat) {
		this.bakimFiyat = bakimFiyat;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "bakimTarihi", nullable = false, length = 19)
	public Date getBakimTarihi() {
		return this.bakimTarihi;
	}

	public void setBakimTarihi(Date bakimTarihi) {
		this.bakimTarihi = bakimTarihi;
	}

}
