package com.liftstore.entity;
// Generated 16 Oca 2021 12:42:51 by Hibernate Tools 5.2.12.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import static org.junit.Assert.assertTrue;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Hammadde generated by hbm2java
 */
@Entity
@Table(name = "hammadde", catalog = "liftstore")
public class Hammadde implements java.io.Serializable {

	private Integer hammaddeId;
	private String hammaddeAdi;
	private int tedarikSuresi;
	private int stokMiktari;
	private float fiyat;
	private Set<Lift> lifts = new HashSet<Lift>(0);

	public Hammadde() {
	}

	public Hammadde(String hammaddeAdi, int tedarikSuresi, int stokMiktari, float fiyat) {
		this.hammaddeAdi = hammaddeAdi;
		this.tedarikSuresi = tedarikSuresi;
		this.stokMiktari = stokMiktari;
		this.fiyat = fiyat;
	}

	public Hammadde(String hammaddeAdi, int tedarikSuresi, int stokMiktari, float fiyat, Set<Lift> lifts) {
		this.hammaddeAdi = hammaddeAdi;
		this.tedarikSuresi = tedarikSuresi;
		this.stokMiktari = stokMiktari;
		this.fiyat = fiyat;
		this.lifts = lifts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "hammaddeID", unique = true, nullable = false)
	public Integer getHammaddeId() {
		return this.hammaddeId;
	}

	public void setHammaddeId(Integer hammaddeId) {
		this.hammaddeId = hammaddeId;
	}

	@Column(name = "hammaddeAdi", nullable = false, length = 100)
	public String getHammaddeAdi() {
		return this.hammaddeAdi;
	}

	public void setHammaddeAdi(String hammaddeAdi) {
		this.hammaddeAdi = hammaddeAdi;
	}

	
	@Column(name = "tedarikSuresi", nullable = false, length = 19)
	public int getTedarikSuresi() {
		return this.tedarikSuresi;
	}

	public void setTedarikSuresi(int tedarikSuresi) {
		this.tedarikSuresi = tedarikSuresi;
	}

	@Column(name = "stokMiktari", nullable = false)
	public int getStokMiktari() {
		return this.stokMiktari;
	}

	public void setStokMiktari(int stokMiktari) {
		this.stokMiktari = stokMiktari;
	}

	@Column(name = "fiyat", nullable = false, precision = 12, scale = 0)
	public float getFiyat() {
		return this.fiyat;
	}

	public void setFiyat(float fiyat) {
		this.fiyat = fiyat;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hammadde")
	public Set<Lift> getLifts() {
		return this.lifts;
	}

	public void setLifts(Set<Lift> lifts) {
		this.lifts = lifts;
	}

}
