package com.liftstore.entity;
// Generated 16 Oca 2021 12:42:51 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Lift generated by hbm2java
 */
@Entity
@Table(name = "lift", catalog = "liftstore")
public class Lift implements java.io.Serializable {

	private Integer liftId;
	private Hammadde hammadde;
	private String seriNo;
	private byte[] resim;
	private int stokMiktari;
	private float fiyat;
	private float liftYukseklik;
	private String liftModeli;
	private Set<Bakim> bakims = new HashSet<Bakim>(0);
	private Set<Musteri> musteris = new HashSet<Musteri>(0);
	private Set<Siparisdetayi> siparisdetayis = new HashSet<Siparisdetayi>(0);

	public Lift() {
	}

	public Lift(Hammadde hammadde, String seriNo, byte[] resim, int stokMiktari, float fiyat, float liftYukseklik,
			String liftModeli) {
		this.hammadde = hammadde;
		this.seriNo = seriNo;
		this.resim = resim;
		this.stokMiktari = stokMiktari;
		this.fiyat = fiyat;
		this.liftYukseklik = liftYukseklik;
		this.liftModeli = liftModeli;
	}

	public Lift(Hammadde hammadde, String seriNo, byte[] resim, int stokMiktari, float fiyat, float liftYukseklik,
			String liftModeli, Set<Bakim> bakims, Set<Musteri> musteris, Set<Siparisdetayi> siparisdetayis) {
		this.hammadde = hammadde;
		this.seriNo = seriNo;
		this.resim = resim;
		this.stokMiktari = stokMiktari;
		this.fiyat = fiyat;
		this.liftYukseklik = liftYukseklik;
		this.liftModeli = liftModeli;
		this.bakims = bakims;
		this.musteris = musteris;
		this.siparisdetayis = siparisdetayis;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "liftID", unique = true, nullable = false)
	public Integer getLiftId() {
		return this.liftId;
	}

	public void setLiftId(Integer liftId) {
		this.liftId = liftId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hammaddeId", nullable = false)
	public Hammadde getHammadde() {
		return this.hammadde;
	}

	public void setHammadde(Hammadde hammadde) {
		this.hammadde = hammadde;
	}

	@Column(name = "seriNo", nullable = false, length = 20)
	public String getSeriNo() {
		return this.seriNo;
	}

	public void setSeriNo(String seriNo) {
		this.seriNo = seriNo;
	}

	@Column(name = "resim", nullable = false)
	public byte[] getResim() {
		return this.resim;
	}

	public void setResim(byte[] resim) {
		this.resim = resim;
	}

	@Column(name = "stokMiktari", nullable = false)
	public int getStokMiktari() {
		return this.stokMiktari;
	}

	public void setStokMiktari(int stokMiktari) {
		this.stokMiktari = stokMiktari;
	}

	@Column(name = "fiyat", nullable = false, precision = 12, scale = 0)
	public float getFiyat() {
		return this.fiyat;
	}

	public void setFiyat(float fiyat) {
		this.fiyat = fiyat;
	}

	@Column(name = "liftYukseklik", nullable = false, precision = 12, scale = 0)
	public float getLiftYukseklik() {
		return this.liftYukseklik;
	}

	public void setLiftYukseklik(float liftYukseklik) {
		this.liftYukseklik = liftYukseklik;
	}

	@Column(name = "liftModeli", nullable = false, length = 20)
	public String getLiftModeli() {
		return this.liftModeli;
	}

	public void setLiftModeli(String liftModeli) {
		this.liftModeli = liftModeli;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lift")
	public Set<Bakim> getBakims() {
		return this.bakims;
	}

	public void setBakims(Set<Bakim> bakims) {
		this.bakims = bakims;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lift")
	public Set<Musteri> getMusteris() {
		return this.musteris;
	}

	public void setMusteris(Set<Musteri> musteris) {
		this.musteris = musteris;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lift")
	public Set<Siparisdetayi> getSiparisdetayis() {
		return this.siparisdetayis;
	}

	public void setSiparisdetayis(Set<Siparisdetayi> siparisdetayis) {
		this.siparisdetayis = siparisdetayis;
	}

	public void setLastUpdateTime(Date date) {
		// TODO Auto-generated method stub
		
	}

}
