package com.liftstore.entity;
// Generated 16 Oca 2021 12:42:51 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Musteri generated by hbm2java
 */
@Entity
@Table(name = "musteri", catalog = "liftstore")
public class Musteri implements java.io.Serializable {

	private Integer musteriId;
	private Lift lift;
	private String telNo;
	private String musteriAdi;
	private String email;

	public Musteri() {
	}

	public Musteri(Lift lift, String telNo, String musteriAdi, String email) {
		this.lift = lift;
		this.telNo = telNo;
		this.musteriAdi = musteriAdi;
		this.email = email;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "musteriID", unique = true, nullable = false)
	public Integer getMusteriId() {
		return this.musteriId;
	}

	public void setMusteriId(Integer musteriId) {
		this.musteriId = musteriId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "liftId", nullable = false)
	public Lift getLift() {
		return this.lift;
	}

	public void setLift(Lift lift) {
		this.lift = lift;
	}

	@Column(name = "telNo", nullable = false, length = 20)
	public String getTelNo() {
		return this.telNo;
	}

	public void setTelNo(String telNo) {
		this.telNo = telNo;
	}

	@Column(name = "musteriAdi", nullable = false, length = 100)
	public String getMusteriAdi() {
		return this.musteriAdi;
	}

	public void setMusteriAdi(String musteriAdi) {
		this.musteriAdi = musteriAdi;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
