package com.liftstore.entity;
// Generated 16 Oca 2021 12:42:51 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Siparisdetayi generated by hbm2java
 */
@Entity
@Table(name = "siparisdetayi", catalog = "liftstore")
public class Siparisdetayi implements java.io.Serializable {

	private SiparisdetayiId id;
	private Lift lift;
	private Siparis siparis;

	public Siparisdetayi() {
	}

	public Siparisdetayi(SiparisdetayiId id, Lift lift, Siparis siparis) {
		this.id = id;
		this.lift = lift;
		this.siparis = siparis;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "siparisId", column = @Column(name = "siparisId", nullable = false)),
			@AttributeOverride(name = "liftId", column = @Column(name = "liftId", nullable = false)),
			@AttributeOverride(name = "siparisAdeti", column = @Column(name = "siparisAdeti", nullable = false)),
			@AttributeOverride(name = "toplamTutar", column = @Column(name = "toplamTutar", nullable = false, precision = 12, scale = 0)) })
	public SiparisdetayiId getId() {
		return this.id;
	}

	public void setId(SiparisdetayiId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "liftId", nullable = false, insertable = false, updatable = false)
	public Lift getLift() {
		return this.lift;
	}

	public void setLift(Lift lift) {
		this.lift = lift;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "siparisId", nullable = false, insertable = false, updatable = false)
	public Siparis getSiparis() {
		return this.siparis;
	}

	public void setSiparis(Siparis siparis) {
		this.siparis = siparis;
	}

}
